### ISSUE TITLE
Would it be possible to reassign some of the default Windows key-bindings?

### ISSUE THREAD

**Issue by jcberquist** [Ortus-Solutions/sublime-commandbox#1]
First of all, thanks for this package, it is really exciting to see it!

It would be nice if alternate default key-bindings could be found for Windows. <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>B</kbd> is the default Windows key binding for selecting a build system variant, while <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>T</kbd> is the default Windows key binding for re-opening the last closed file, and <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> is the default key binding for showing the command palette overlay.

**Comment by lmajano** [comment]
Would you be willing to help?

**Comment by jcberquist** [comment]
I am happy to offer a possible alternative :smile: 

The <kbd>ALT</kbd> key could be used instead of the <kbd>CTRL</kbd> key in the above bindings. <kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>B|T|P</kbd> is not used in the default key bindings. Would that work?

**Comment by lmajano** [comment]
I actually think that in sublime you can do alternative for each OS, can you help me find that documentation on how to do this?

**Comment by jcberquist** [comment]
Yes, as you have in the root of this repository: `Default (Windows).sublime-keymap`,`Default (OSX).sublime-keymap`, and `Default (Linux).sublime-keymap`. Sublime Text automatically applies the one that references the OS it is running on. 

You can read more here: http://docs.sublimetext.info/en/latest/reference/key_bindings.html

I took a look at the default key bindings for OSX and Linux. OSX is different since the key bindings tend to use <kbd>CMD</kbd> over <kbd>CTRL</kbd>. Only <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> is already bound to a command (`show_scope_name`) but <kbd>CMD</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> is bound to the same command, so I wouldn't think it would be a problem to overwrite it. Linux on the other hand is the same as Windows, so if the windows bindings are changed, the Linux ones should probably be as well.

**Comment by m1waterman88** [comment]
Hey, guys. Was there a solution to this? I just installed this package in Sublime Text 3 on Linux, and I can't use the shortcut keys to the Command Palette (CTRL+SHIFT+P). I checked the default keybindings to the Command Palette, which were correct, and there were no user settings. Then I reviewed the CommandBox package's keybindings to find that stop server was set to CTRL+SHIFT+S+P, with no keybindings used for CTRL+SHIFT+P. (The GitHub README shows stop server as CTRL+SHIFT+P.) However, CTRL+SHIFT+P is still calling the CommandBox package. Found in two parts:

1. I entered the below commands in the Sublime console:
```
sublime.log_commands(True)
sublime.log_input(True)
```
2. I then tested the key binding CTRL+SHIFT+P, with these results:
```
key evt: shift+control+p
command: commandbox {"task_name": "server_stop"}
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1050, in run_
    return self.run(**args)
  File "/home/user/.config/sublime-text-3/Installed Packages/Commandbox.sublime-package/BaseCommand.py", line 28, in run
  File "/home/user/.config/sublime-text-3/Installed Packages/Commandbox.sublime-package/BaseCommand.py", line 90, in projectPath
IndexError: list index out of range
```
NOTE: I substituted my username for "user."

If I remove the package, my normal Sublime functionality is restored.
